/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/walle.glb -t 
*/

import * as THREE from 'three'
//import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Solid1: THREE.Mesh
    Solid1_1: THREE.Mesh
    Solid1_2: THREE.Mesh
    Solid1_3: THREE.Mesh
    Solid1_4: THREE.Mesh
    Solid1_18: THREE.Mesh
    Solid1_19: THREE.Mesh
    Solid2_1: THREE.Mesh
    Solid2_2: THREE.Mesh
    Solid3_1: THREE.Mesh
    Solid3_2: THREE.Mesh
    Solid4: THREE.Mesh
    Solid5: THREE.Mesh
    Solid6: THREE.Mesh
    Solid7: THREE.Mesh
    Solid8: THREE.Mesh
    Solid9: THREE.Mesh
    Solid10: THREE.Mesh
    Solid11: THREE.Mesh
    Solid12: THREE.Mesh
    Solid13: THREE.Mesh
    Solid14: THREE.Mesh
    Solid15: THREE.Mesh
    Solid16: THREE.Mesh
    Solid17: THREE.Mesh
    Solid18: THREE.Mesh
    Solid19: THREE.Mesh
    Solid20: THREE.Mesh
    Solid21: THREE.Mesh
    Solid24: THREE.Mesh
    Solid25: THREE.Mesh
    Solid26: THREE.Mesh
    Solid27: THREE.Mesh
    Solid28: THREE.Mesh
    Solid29: THREE.Mesh
    Solid30: THREE.Mesh
    Solid31: THREE.Mesh
    Solid32: THREE.Mesh
    Solid33: THREE.Mesh
    Solid34: THREE.Mesh
    Solid35: THREE.Mesh
    Solid36: THREE.Mesh
    Solid37: THREE.Mesh
    Solid38: THREE.Mesh
    Solid39: THREE.Mesh
    Solid40: THREE.Mesh
    Solid41: THREE.Mesh
    Solid42: THREE.Mesh
    Solid43: THREE.Mesh
    Solid44: THREE.Mesh
    Solid45: THREE.Mesh
    Solid46: THREE.Mesh
    Solid47: THREE.Mesh
    Solid48: THREE.Mesh
    Solid49: THREE.Mesh
    Solid50: THREE.Mesh
    Solid51: THREE.Mesh
    Solid52: THREE.Mesh
    Solid53: THREE.Mesh
    Solid54: THREE.Mesh
    Solid55: THREE.Mesh
    Solid56: THREE.Mesh
    Solid57: THREE.Mesh
    Solid58: THREE.Mesh
    Solid59: THREE.Mesh
    Solid60: THREE.Mesh
    Solid1_6: THREE.Mesh
    Solid1_7: THREE.Mesh
    Solid1_8: THREE.Mesh
    Solid1_9: THREE.Mesh
    Solid1_10: THREE.Mesh
    Solid1_11: THREE.Mesh
    Solid1_12: THREE.Mesh
  }
  materials: {
    XID_Default2_7150A396A8A9425682E0F81D8C6823AB_shader: THREE.MeshStandardMaterial
    XID_Default3_334A97E776534CDFBBBB6F1D0FA4FF78_shader: THREE.MeshStandardMaterial
    XID_245245245_EECA1C1961214EEDBFDDA33907415D01_shader: THREE.MeshStandardMaterial
    XID_2437248_91269B81DC204ED2B0215A66BEBD10E8_shader: THREE.MeshStandardMaterial
    XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader: THREE.MeshStandardMaterial
    XID_323232_E79EE52310D9458EB20D78C74F632D0A_shader: THREE.MeshStandardMaterial
    XID_101010_A4A79F1724104594835510BCF35DE786_shader: THREE.MeshStandardMaterial
    XID_Default1_A605CDE535F9458ABB5B809227B17EC9_shader: THREE.MeshStandardMaterial
  }
  
}

//type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/walle.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0.021, -0.011, 0]}>
        <mesh geometry={nodes.Solid1.geometry} material={materials.XID_Default2_7150A396A8A9425682E0F81D8C6823AB_shader} scale={0.01} />
      </group>
      <group position={[0.021, 0.049, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
        <mesh geometry={nodes.Solid1_1.geometry} material={materials.XID_Default2_7150A396A8A9425682E0F81D8C6823AB_shader} scale={0.01} />
      </group>
      <group position={[0.021, 0.055, 0]} rotation={[0, 0.037, 0]}>
        <mesh geometry={nodes.Solid1_2.geometry} material={materials.XID_Default2_7150A396A8A9425682E0F81D8C6823AB_shader} scale={0.01} />
      </group>
      <group position={[0.056, 0.043, 0.078]} rotation={[-3.134, 0.086, -3.141]}>
        <mesh geometry={nodes.Solid1_3.geometry} material={materials.XID_Default2_7150A396A8A9425682E0F81D8C6823AB_shader} scale={0.01} />
      </group>
      <group position={[0.023, 0.081, 0.026]} rotation={[2.986, -0.036, 3.136]}>
        <mesh geometry={nodes.Solid1_4.geometry} material={materials.XID_Default3_334A97E776534CDFBBBB6F1D0FA4FF78_shader} scale={0.01} />
      </group>
      <group position={[0.044, 0.07, 0.015]} rotation={[2.986, -0.036, 3.136]}>
        <group scale={0.01}>
          <mesh geometry={nodes.Solid1_18.geometry} material={materials.XID_245245245_EECA1C1961214EEDBFDDA33907415D01_shader} />
          <mesh geometry={nodes.Solid1_19.geometry} material={materials.XID_2437248_91269B81DC204ED2B0215A66BEBD10E8_shader} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.Solid2_1.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} />
          <mesh geometry={nodes.Solid2_2.geometry} material={materials.XID_323232_E79EE52310D9458EB20D78C74F632D0A_shader} />
        </group>
        <group scale={0.01}>
          <mesh geometry={nodes.Solid3_1.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} />
          <mesh geometry={nodes.Solid3_2.geometry} material={materials.XID_101010_A4A79F1724104594835510BCF35DE786_shader} />
        </group>
        <mesh geometry={nodes.Solid4.geometry} material={materials.XID_323232_E79EE52310D9458EB20D78C74F632D0A_shader} scale={0.01} />
        <mesh geometry={nodes.Solid5.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid6.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid7.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid8.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid9.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid10.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid11.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid12.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid13.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid14.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid15.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid16.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid17.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid18.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid19.geometry} material={materials.XID_323232_E79EE52310D9458EB20D78C74F632D0A_shader} scale={0.01} />
        <mesh geometry={nodes.Solid20.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid21.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid24.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid25.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid26.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid27.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid28.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid29.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid30.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid31.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid32.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid33.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid34.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid35.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid36.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid37.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid38.geometry} material={materials.XID_323232_E79EE52310D9458EB20D78C74F632D0A_shader} scale={0.01} />
        <mesh geometry={nodes.Solid39.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid40.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid41.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid42.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid43.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid44.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid45.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid46.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid47.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid48.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid49.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid50.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid51.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid52.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid53.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid54.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid55.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid56.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid57.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid58.geometry} material={materials.XID_164164164_B52A057B48374CC48D775011F4AA62A5_shader} scale={0.01} />
        <mesh geometry={nodes.Solid59.geometry} material={materials.XID_323232_E79EE52310D9458EB20D78C74F632D0A_shader} scale={0.01} />
        <mesh geometry={nodes.Solid60.geometry} material={materials.XID_323232_E79EE52310D9458EB20D78C74F632D0A_shader} scale={0.01} />
      </group>
      <group position={[0.008, 0.079, 0.011]} rotation={[2.986, -0.036, 3.136]}>
        <mesh geometry={nodes.Solid1_6.geometry} material={materials.XID_Default3_334A97E776534CDFBBBB6F1D0FA4FF78_shader} scale={0.01} />
      </group>
      <group position={[0.053, 0.03, -0.006]} rotation={[-Math.PI / 2, 0, -3.023]}>
        <mesh geometry={nodes.Solid1_7.geometry} material={materials.XID_Default2_7150A396A8A9425682E0F81D8C6823AB_shader} scale={0.01} />
      </group>
      <group position={[0.06, 0.031, 0.033]} rotation={[0, -0.012, 0]}>
        <mesh geometry={nodes.Solid1_8.geometry} material={materials.XID_Default3_334A97E776534CDFBBBB6F1D0FA4FF78_shader} scale={0.01} />
      </group>
      <group position={[-0.033, 0.03, -0.007]} rotation={[-Math.PI / 2, 0, -3.055]}>
        <mesh geometry={nodes.Solid1_9.geometry} material={materials.XID_Default2_7150A396A8A9425682E0F81D8C6823AB_shader} scale={0.01} />
      </group>
      <group position={[-0.028, 0.031, 0.032]} rotation={[0, -0.196, 0]}>
        <mesh geometry={nodes.Solid1_10.geometry} material={materials.XID_Default3_334A97E776534CDFBBBB6F1D0FA4FF78_shader} scale={0.01} />
      </group>
      <group position={[0.054, -0.011, 0.033]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_11.geometry} material={materials.XID_Default1_A605CDE535F9458ABB5B809227B17EC9_shader} scale={0.01} />
      </group>
      <group position={[-0.018, -0.011, 0.033]} rotation={[Math.PI / 2, Math.PI / 2, 0]}>
        <mesh geometry={nodes.Solid1_12.geometry} material={materials.XID_Default1_A605CDE535F9458ABB5B809227B17EC9_shader} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/walle.glb')
